-- Esquema y datos de la primera versión del sistema (productos sin código ni existencias, usuarios con rol).
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    rol VARCHAR(10) NOT NULL
);
CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(60) NOT NULL,
    descripcion VARCHAR(500),
    estado VARCHAR(10) NOT NULL
);
INSERT INTO usuario (username, password, rol) VALUES ('admin', 'hash-viejo', 'ADMIN');
INSERT INTO producto (nombre, categoria, descripcion, estado) VALUES ('Martillo heredado', 'Herramientas', 'Del sistema anterior', 'ACTIVO');
INSERT INTO producto (nombre, categoria, descripcion, estado) VALUES ('Taladro heredado', 'Eléctricas', NULL, 'INACTIVO');
